### ISSUE TITLE
Migrating from socket.io-redis to @socket.io/redis-adapter

### ISSUE THREAD

**Issue by rishighan** [moleculerjs/moleculer-io#53]
Hello,

I upgraded my `socket.io-redis` package to `@socket.io/redis-adapter` (package was renamed in `7.0`) As part of the [instructions to migrate](https://github.com/socketio/socket.io-redis-adapter#migrating-from-socketio-redis) it expects an explicit creation of a Redis `pub` and `sub` instances. Furthermore, in the `settings` object of my service schema, I used to have this:

```typescript
//...
options: {
    adapter: redisAdapter({
        host: redisURL.hostname,
        port: 6379,
    }),
},
//...
```

And with the changes suggested by `@socket.io/redis-adapter`, 

```typescript
import { createClient } from "redis";
import { createAdapter } from "@socket.io/redis-adapter";

const pubClient = createClient({ url: `redis://${redisURL.hostname}:6379` });
const subClient = pubClient.duplicate();

//...

options: {
    adapter: createAdapter(pubClient, subClient),
},
```

throws an error with this stack trace:

```console
ClientClosedError: The client is closed
    at Commander._RedisClient_sendCommand (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/client/index.js:482:31)
    at Commander.commandsExecutor (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/client/index.js:193:154)
    at Commander.BaseClass.<computed> [as publish] (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/commander.js:8:29)
    at RedisAdapter.broadcast (/Users/rishi/work/threetwo-core-service/node_modules/@socket.io/redis-adapter/dist/index.js:473:28)
    at BroadcastOperator.emit (/Users/rishi/work/threetwo-core-service/node_modules/socket.io/dist/broadcast-operator.js:125:26)
    at Namespace.emit (/Users/rishi/work/threetwo-core-service/node_modules/socket.io/dist/namespace.js:170:73)
    at SocketService.handler (/Users/rishi/work/threetwo-core-service/node_modules/moleculer-io/src/index.js:214:16)
    at /Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/utils.js:212:22
    at processCheckResponse (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/validators/base.js:63:29)
    at validateContextParams (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/validators/base.js:88:15)
    at ServiceBroker.timeoutMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/timeout.js:31:14)
    at ServiceBroker.fallbackMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/fallback.js:31:11)
    at ServiceBroker.errorHandlerMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
    at ServiceBroker.tracingLocalActionMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/tracing.js:101:12)
    at ServiceBroker.call (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/service-broker.js:1215:31)
    at Queue.<anonymous> (/Users/rishi/work/threetwo-core-service/services/importqueue.service.ts:248:25) {
  [stack]: 'Error: The client is closed\n' +
    '    at Commander._RedisClient_sendCommand (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/client/index.js:482:31)\n' +
    '    at Commander.commandsExecutor (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/client/index.js:193:154)\n' +
    '    at Commander.BaseClass.<computed> [as publish] (/Users/rishi/work/threetwo-core-service/node_modules/@redis/client/dist/lib/commander.js:8:29)\n' +
    '    at RedisAdapter.broadcast (/Users/rishi/work/threetwo-core-service/node_modules/@socket.io/redis-adapter/dist/index.js:473:28)\n' +
    '    at BroadcastOperator.emit (/Users/rishi/work/threetwo-core-service/node_modules/socket.io/dist/broadcast-operator.js:125:26)\n' +
    '    at Namespace.emit (/Users/rishi/work/threetwo-core-service/node_modules/socket.io/dist/namespace.js:170:73)\n' +
    '    at SocketService.handler (/Users/rishi/work/threetwo-core-service/node_modules/moleculer-io/src/index.js:214:16)\n' +
    '    at /Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/utils.js:212:22\n' +
    '    at processCheckResponse (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/validators/base.js:63:29)\n' +
    '    at validateContextParams (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/validators/base.js:88:15)\n' +
    '    at ServiceBroker.timeoutMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/timeout.js:31:14)\n' +
    '    at ServiceBroker.fallbackMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/fallback.js:31:11)\n' +
    '    at ServiceBroker.errorHandlerMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/error-handler.js:14:10)\n' +
    '    at ServiceBroker.tracingLocalActionMiddleware (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/middlewares/tracing.js:101:12)\n' +
    '    at ServiceBroker.call (/Users/rishi/work/threetwo-core-service/node_modules/moleculer/src/service-broker.js:1215:31)\n' +
    '    at Queue.<anonymous> (/Users/rishi/work/threetwo-core-service/services/importqueue.service.ts:248:25)',
  [message]: 'The client is closed'
}

```

What am I doing wrong?

**Comment by icebob** [comment]
I don't think it's a moleculer.io related issue because you should configure redis adapter explicitly, moleculer-io don't know about it, no any Redis relevant code in the codebase.

**Comment by rishighan** [comment]
You are right, yet again @icebob, it was an errant `redis` dependency that was throwing this error. I updated it to the latest version and it went away.
